image: python:3.8.2

pipelines:
  branches:
    development:
      - step:
          name: Verify code
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - pytest ./
